### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by sirrus** [ct-Open-Source/team-container#3]
Hi,

i've got traefik up and running - especially with letsencrypt for my domains.

But I've installed Rocket Chat and Jitsi and none of them is showing up - on both URLs it's just showing: 404 page not found

What can i do to fix it?

Regards,
Andreas

**Comment by chjohn22** [comment]
Did you create matching DNS-Records for the corresponding subdomains?

**Comment by sirrus** [comment]
> Did you create matching DNS-Records for the corresponding subdomains?

Yes - I have 4 records. All Type A

- remote.domain.tld (traefik)
- cloud.domain.tld (nextcloud)
- chat.domain.tld (rocketchat)
- video.domain.tld (jitsi)

Resolving to the external IP address.

**Comment by NiWo90** [comment]
> Delivered Content:
> 
> * remote.domain.tld = nginx default
> * cloud.domain.tld = 404 page not found
> * chat.domain.tld = 404 page not found
> * video.domain.tld = 404 page not found

I have the same Issue right now... nextcloud was working for a couple of minutes and then all sites went back to 404 and the traefik site went down to ERR_TIMED_OUT...

**Comment by sirrus** [comment]
Yes - same here now - all down - time out... ?!??!

**Comment by sirrus** [comment]
I've started from Scratch - just router - waited for 20 minutes. Up and running with letsencrypt...
Then nextcloud - afer 10-20 minutes its all down!?!?

**Comment by jamct** [comment]
Never had this problem. Our test servers are working for weeks now.
Some debugging tips:
- `kubectl get pods` (list pod names)
- `kubectl log <name of pod>` to see what happened inside

**Comment by sirrus** [comment]
I've upgraded kubernetes now:
```

 * Kubernetes 1.18 GA is now available! See https://microk8s.io for docs or
   install it with:

     sudo snap install microk8s --channel=1.18 --classic
```

And this is the output:

```
❯ kubectl get pods
NAME                                              READY   STATUS    RESTARTS   AGE
nextcloud-team-nextcloud-redis-57bcd95c56-4khm5   1/1     Running   0          10h
nextcloud-team-nextcloud-nc-67f7df7dbb-mnd56      0/2     Evicted   0          10h
nextcloud-team-nextcloud-nc-67f7df7dbb-gfbjd      0/2     Pending   0          10h
landingpage-68cb944dd8-zn6gd                      0/1     Evicted   0          10h
landingpage-68cb944dd8-x925s                      0/1     Pending   0          10h
traefik-7c6f69d546-4xg4c                          0/1     Evicted   0          10h
traefik-7c6f69d546-4sk9t                          0/1     Pending   0          5h15m
nextcloud-team-nextcloud-db-7ff5f88d54-w69ks      0/1     Evicted   0          10h
nextcloud-team-nextcloud-db-7ff5f88d54-drgd2      0/1     Pending   0          94s
svclb-traefik-bhjmn                               0/2     Evicted   0          61s
```

**Comment by sirrus** [comment]
And its kubeclt logs <name of pod> - but:

```
❯ kubectl logs svclb-traefik-bhjmn
Error from server (NotFound): pods "svclb-traefik-bhjmn" not found
```

**Comment by jamct** [comment]
Oh I see! Did you install microk8s? This projects is using k3s.
What you saw on the command line is some kind of advertisement by Ubuntu (it is their Kubernetes distro)!
I think you have two Kubernetes instances on one machine now – it will not work. Uninstall this snap package.

**Comment by sirrus** [comment]
Good to know - unistalled - but no change:

```
❯ kubectl get pods
NAME                                              READY   STATUS    RESTARTS   AGE
nextcloud-team-nextcloud-redis-57bcd95c56-4khm5   1/1     Running   0          11h
nextcloud-team-nextcloud-nc-67f7df7dbb-mnd56      0/2     Evicted   0          11h
landingpage-68cb944dd8-zn6gd                      0/1     Evicted   0          11h
traefik-7c6f69d546-4xg4c                          0/1     Evicted   0          11h
nextcloud-team-nextcloud-db-7ff5f88d54-w69ks      0/1     Evicted   0          11h
landingpage-68cb944dd8-x925s                      1/1     Running   0          11h
traefik-7c6f69d546-4sk9t                          0/1     Evicted   0          6h21m
traefik-7c6f69d546-cc44l                          0/1     Pending   0          60m
nextcloud-team-nextcloud-db-7ff5f88d54-drgd2      0/1     Evicted   0          67m
nextcloud-team-nextcloud-db-7ff5f88d54-skm4t      0/1     Pending   0          53m
nextcloud-team-nextcloud-nc-67f7df7dbb-gfbjd      0/2     Evicted   0          11h
nextcloud-team-nextcloud-nc-67f7df7dbb-4nzwc      0/2     Pending   0          51m
svclb-traefik-jjs6r                               0/2     Evicted   0          6m4s
```

**Comment by NiWo90** [comment]
I started all over again with a Fresh Ubuntu-Server 19.10 and it works fine from my side now!

**Comment by CzernyJ** [comment]
Looks like I´ve got the same issue.

When I install jitsi or nextcloud the pods do not start and get evicted shortly thereafter.

Managed to catch it right when starting:
`
$ kubectl get pods
NAME                                              READY   STATUS         RESTARTS   AGE
landingpage-547d6bddc6-6gx57                      1/1     Running        0          20h
svclb-traefik-g4ldf                               2/2     Running        0          20h
traefik-7d45b4b697-kdrjv                          1/1     Running        0          20h
nextcloud-team-nextcloud-redis-7b9d877795-w6r46   1/1     Running        0          60s
nextcloud-team-nextcloud-nc-d55567b79-tqwmz       0/2     ErrImagePull   0          60s
nextcloud-team-nextcloud-db-6dccbd4667-x2x5j      1/1     Running        0          60s
`

Shortly after the pods are evicted:

`
$ kubectl get pods
NAME                                              READY   STATUS    RESTARTS   AGE
landingpage-547d6bddc6-6gx57                      1/1     Running   0          20h
svclb-traefik-g4ldf                               2/2     Running   0          20h
nextcloud-team-nextcloud-redis-7b9d877795-w6r46   1/1     Running   0          2m3s
nextcloud-team-nextcloud-nc-d55567b79-tqwmz       0/2     Evicted   0          2m3s
nextcloud-team-nextcloud-nc-d55567b79-pjq6s       0/2     Pending   0          24s
traefik-7d45b4b697-kdrjv                          0/1     Evicted   0          20h
traefik-7d45b4b697-zbw4l                          0/1     Pending   0          23s
nextcloud-team-nextcloud-db-6dccbd4667-x2x5j      1/1     Running   1          2m3s
`

When I `kubectl describe pods`on an evicted pod I get:

`Events:
  Type     Reason               Age                  From               Message
  ----     ------               ----                 ----               -------
  Normal   Scheduled            <unknown>            default-scheduler  Successfully assigned default/nextcloud-team-nextcloud-nc-d55567b79-tqwmz to vsogi
  Warning  Failed               85s                  kubelet, vsogi     Failed to pull image "nextcloud:stable": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nextcloud:stable": unpack: failed to extract layer sha256:7cc1639e12af6e9e4fc708d77af39e22a6e976c239c40fbfea4f6df2b01a0814: write /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/280/fs/usr/local/lib/php/extensions/no-debug-non-zts-20180731/redis.so: no space left on device: unknown
  Warning  Failed               85s                  kubelet, vsogi     Error: ImagePullBackOff
  Normal   BackOff              85s                  kubelet, vsogi     Back-off pulling image "nextcloud:stable"
  Normal   Pulling              73s (x2 over 2m11s)  kubelet, vsogi     Pulling image "nextcloud:stable"
  Warning  Evicted              72s                  kubelet, vsogi     The node was low on resource: ephemeral-storage.
  Warning  ExceededGracePeriod  62s                  kubelet, vsogi     Container runtime did not kill the pod within specified grace period.
  Warning  Failed               39s                  kubelet, vsogi     Failed to pull image "nextcloud:stable": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nextcloud:stable": unpack: failed to extract layer sha256:837bf4bf6e080c639eb860643014d6b6c4a3cd2e53e4ed28b6d24a3314071589: write /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/287/fs/usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6: no space left on device: unknown
  Warning  Failed               39s (x2 over 85s)    kubelet, vsogi     Error: ErrImagePull
  Normal   BackOff              39s (x3 over 85s)    kubelet, vsogi     Back-off pulling image "nextcloud:stable"
  Warning  Failed               39s (x3 over 85s)    kubelet, vsogi     Error: ImagePullBackOff
`

Saying the node was low on ephemeral-storage. Which is strange, because with only running the k3s and nextcloud it should be nowhere near 400GB of storage.

**Comment by sirrus** [comment]
I've finally fixed it - I've tried to upgrade from 18.04LTS to 20.04LTS. This didn't work right away - the lvm logical volume was to small (4GB). I've resized it to 20GB and it upgraded as it should.

Once upgraded and with more space all services started to wor properly.

**Comment by sirrus** [comment]
And a note for the impatient people - it really takes some time and you can check it with:

```
❯ kubectl get pods
NAME                                              READY   STATUS              RESTARTS   AGE
landingpage-68cb944dd8-zn6gd                      0/1     Evicted             0          8d
traefik-7c6f69d546-4xg4c                          0/1     Evicted             0          8d
traefik-7c6f69d546-4sk9t                          0/1     Evicted             0          8d
landingpage-68cb944dd8-x925s                      0/1     Evicted             0          8d
traefik-7c6f69d546-cc44l                          0/1     Evicted             0          8d
landingpage-68cb944dd8-kh78v                      0/1     Evicted             0          50m
svclb-traefik-rdc5m                               2/2     Running             2          29m
traefik-7c6f69d546-nj2wq                          1/1     Running             1          46m
landingpage-68cb944dd8-xx4g6                      1/1     Running             1          45m
nextcloud-team-nextcloud-redis-6d7d46ddf5-624lj   1/1     Running             0          10m
nextcloud-team-nextcloud-db-867476f447-5vfsf      1/1     Running             0          10m
nextcloud-team-nextcloud-nc-58694d95f7-g296h      2/2     Running             0          10m
chat-team-chat-mongo-mqlj9                        2/2     Running             0          10m
chat-team-chat-rc-5c4d77889f-rgjfq                1/1     Running             0          10m
video-team-video-prosody-856995bc6b-snmpl         0/1     ContainerCreating   0          2m18s
video-team-video-jicofo-7977ccf7cd-xwvwh          0/1     ContainerCreating   0          2m18s
video-team-video-jvb-59f798d655-vxp24             0/1     ContainerCreating   0          2m18s
video-team-video-web-6db87bf877-6jqws             0/1     ContainerCreating   0          2m18s
```

Youd should wait until ContainerCreating is switching to Running.

**Comment by CzernyJ** [comment]
Ok I as well did fix my problem, seems like my server didn't have enough disk space properly allocated. Of my 400 GBs only 4 GB were properly formatted and mounted.

I solved this by creating a big enough logical volume and mounting it at: `/var/lib/rancher/k3s/storage` where k3s is putting the default of its local-storage pvc.
This is best done before installing the router, because you may have to copy the routers pv around.

You won't encounter this problem if your server has one big partition it works on, but since I used the ubuntu 18.04 defaults (enabling LVM) you may have to finetune.

And @sirrus is right. It really does take some time for nextcloud to start.
